/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.filmequipmentrentalservice;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil Patrick
 */
public class AdminDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AdminDashBoard() {
        initComponents();
        refreshEquipmentList();
        refreshCategoryList();
        refreshCustomerList();
        refreshTransactionList();
        clearCustomerForm();

        List<Category> categories = CategoryService.getAllCategories();

        for (int i = 0; i < categories.size(); i++) {
            equipmentCategoryCombobox.addItem(categories.get(i).name);
        }

        filterComboBox.addItem("All categories");

        for (int i = 0; i < categories.size(); i++) {
            filterComboBox.addItem(categories.get(i).name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        log_outButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        equipmentTab = new javax.swing.JPanel();
        equipmentFormTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipmentsTable = new javax.swing.JTable();
        EqupmentNameLabel1 = new javax.swing.JLabel();
        EqupmentNameLabel2 = new javax.swing.JLabel();
        EqupmentNameLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        equipmentDailyFeeInputField = new javax.swing.JTextField();
        equipmentNameInputField = new javax.swing.JTextField();
        equipmentWeeklyFeeInputField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addEquipmentBtn = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        updateEquipmentButton = new javax.swing.JButton();
        equipmentCategoryCombobox = new javax.swing.JComboBox<>();
        filterComboBox = new javax.swing.JComboBox<>();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        scrollpaneDescription = new javax.swing.JScrollPane();
        dscriptionTextArea = new javax.swing.JTextArea();
        CustomerTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CustomerPane = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        ucstomerNameLabel1 = new javax.swing.JLabel();
        customerEmailLabel2 = new javax.swing.JLabel();
        ucstomerNameLabel3 = new javax.swing.JLabel();
        ucstomerNameLabel4 = new javax.swing.JLabel();
        customerEmailTextFeild = new javax.swing.JTextField();
        customerUsernameTextFeild = new javax.swing.JTextField();
        customerPhoneTextFeild = new javax.swing.JTextField();
        customerAddressTextFeild = new javax.swing.JTextField();
        ucstomerNameLabel2 = new javax.swing.JLabel();
        customerNameTextFeild1 = new javax.swing.JTextField();
        UpdateCustomerButton = new javax.swing.JButton();
        refreshCustomerButton1 = new javax.swing.JButton();
        transactionTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionListTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        CategoryTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoryNameTextField1 = new javax.swing.JTextField();
        AddCategoryButton = new javax.swing.JButton();
        categoriesPane = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        refreshCategoryButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 75, 75));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 65));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Film Equipment Rental Service");

        log_outButton.setBackground(new java.awt.Color(255, 255, 255));
        log_outButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        log_outButton.setForeground(new java.awt.Color(0, 75, 75));
        log_outButton.setText("Log out");
        log_outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(log_outButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log_outButton)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setName("Customers"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 425));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        equipmentTab.setBackground(new java.awt.Color(255, 255, 255));
        equipmentTab.setForeground(new java.awt.Color(0, 0, 0));

        equipmentFormTitle.setBackground(new java.awt.Color(255, 255, 255));
        equipmentFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equipmentFormTitle.setForeground(new java.awt.Color(0, 102, 102));
        equipmentFormTitle.setText("Add Equipments");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        equipmentsTable.setBackground(new java.awt.Color(255, 255, 255));
        equipmentsTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        equipmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipment ID", "Equipment Name", "Description", "Daily Fee", "Weekly Fee", "Category ", "Is Available Today", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentsTable.setToolTipText("");
        equipmentsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        equipmentsTable.setPreferredSize(new java.awt.Dimension(300, 300));
        equipmentsTable.setRequestFocusEnabled(false);
        equipmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(equipmentsTable);

        EqupmentNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel1.setText("Equipment Name");

        EqupmentNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel2.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel2.setText("Description");

        EqupmentNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel3.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel3.setText("Daily Fee");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Weekly Fee");

        equipmentDailyFeeInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentDailyFeeInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentDailyFeeInputField.setMinimumSize(new java.awt.Dimension(4, 19));
        equipmentDailyFeeInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentDailyFeeInputFieldActionPerformed(evt);
            }
        });

        equipmentNameInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentNameInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentNameInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        equipmentWeeklyFeeInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentWeeklyFeeInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentWeeklyFeeInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Category");

        addEquipmentBtn.setBackground(new java.awt.Color(0, 102, 102));
        addEquipmentBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addEquipmentBtn.setText("Add");
        addEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEquipmentBtnActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        updateEquipmentButton.setBackground(new java.awt.Color(0, 102, 102));
        updateEquipmentButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updateEquipmentButton.setText("Update");
        updateEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEquipmentButtonActionPerformed(evt);
            }
        });

        equipmentCategoryCombobox.setBackground(new java.awt.Color(255, 255, 255));
        equipmentCategoryCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        equipmentCategoryCombobox.setForeground(new java.awt.Color(0, 102, 102));
        equipmentCategoryCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentCategoryComboboxActionPerformed(evt);
            }
        });

        filterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterComboBoxItemStateChanged(evt);
            }
        });

        statusComboBox.setBackground(new java.awt.Color(255, 255, 255));
        statusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(0, 102, 102));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Status");

        dscriptionTextArea.setBackground(new java.awt.Color(255, 255, 255));
        dscriptionTextArea.setColumns(20);
        dscriptionTextArea.setRows(5);
        dscriptionTextArea.setBorder(null);
        scrollpaneDescription.setViewportView(dscriptionTextArea);

        javax.swing.GroupLayout equipmentTabLayout = new javax.swing.GroupLayout(equipmentTab);
        equipmentTab.setLayout(equipmentTabLayout);
        equipmentTabLayout.setHorizontalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EqupmentNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(EqupmentNameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scrollpaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(equipmentDailyFeeInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(equipmentFormTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EqupmentNameLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(equipmentNameInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(equipmentWeeklyFeeInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipmentCategoryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(addEquipmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(602, 602, 602)
                .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        equipmentTabLayout.setVerticalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqupmentNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(equipmentFormTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EqupmentNameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EqupmentNameLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipmentDailyFeeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipmentWeeklyFeeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(equipmentCategoryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEquipmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Equipments", equipmentTab);

        CustomerTab.setBackground(new java.awt.Color(255, 255, 255));
        CustomerTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        CustomerTab.setForeground(new java.awt.Color(0, 102, 102));
        CustomerTab.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        CustomerTab.setName("Customers"); // NOI18N
        CustomerTab.setPreferredSize(new java.awt.Dimension(850, 325));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("All Customers");

        CustomerPane.setBackground(new java.awt.Color(255, 255, 255));
        CustomerPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Email", "Phone Number", "Username", "Address"
            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        CustomerPane.setViewportView(CustomerTable);

        ucstomerNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ucstomerNameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        ucstomerNameLabel1.setText("Address");

        customerEmailLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerEmailLabel2.setForeground(new java.awt.Color(0, 102, 102));
        customerEmailLabel2.setText("Email");

        ucstomerNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ucstomerNameLabel3.setForeground(new java.awt.Color(0, 102, 102));
        ucstomerNameLabel3.setText("Phone Number");

        ucstomerNameLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ucstomerNameLabel4.setForeground(new java.awt.Color(0, 102, 102));
        ucstomerNameLabel4.setText("Username");

        customerEmailTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        customerEmailTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerEmailTextFeild.setForeground(new java.awt.Color(0, 102, 102));

        customerUsernameTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        customerUsernameTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerUsernameTextFeild.setForeground(new java.awt.Color(0, 102, 102));

        customerPhoneTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        customerPhoneTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerPhoneTextFeild.setForeground(new java.awt.Color(0, 102, 102));

        customerAddressTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        customerAddressTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerAddressTextFeild.setForeground(new java.awt.Color(0, 102, 102));

        ucstomerNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ucstomerNameLabel2.setForeground(new java.awt.Color(0, 102, 102));
        ucstomerNameLabel2.setText("Name");

        customerNameTextFeild1.setBackground(new java.awt.Color(255, 255, 255));
        customerNameTextFeild1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerNameTextFeild1.setForeground(new java.awt.Color(0, 102, 102));

        UpdateCustomerButton.setBackground(new java.awt.Color(0, 102, 102));
        UpdateCustomerButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UpdateCustomerButton.setText("Update");
        UpdateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerButtonActionPerformed(evt);
            }
        });

        refreshCustomerButton1.setBackground(new java.awt.Color(0, 102, 102));
        refreshCustomerButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        refreshCustomerButton1.setText("Refresh");
        refreshCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCustomerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerTabLayout = new javax.swing.GroupLayout(CustomerTab);
        CustomerTab.setLayout(CustomerTabLayout);
        CustomerTabLayout.setHorizontalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameTextFeild1)
                            .addComponent(customerUsernameTextFeild)
                            .addComponent(customerAddressTextFeild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(customerEmailTextFeild)
                            .addComponent(customerPhoneTextFeild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ucstomerNameLabel3)
                            .addComponent(ucstomerNameLabel4)
                            .addComponent(ucstomerNameLabel1)
                            .addComponent(customerEmailLabel2)
                            .addComponent(ucstomerNameLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerTabLayout.createSequentialGroup()
                        .addComponent(UpdateCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshCustomerButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(CustomerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CustomerTabLayout.setVerticalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(ucstomerNameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerNameTextFeild1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerEmailLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerEmailTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ucstomerNameLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerPhoneTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ucstomerNameLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerUsernameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ucstomerNameLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(customerAddressTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateCustomerButton)
                            .addComponent(refreshCustomerButton1))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customers", CustomerTab);

        transactionTab.setBackground(new java.awt.Color(255, 255, 255));
        transactionTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionTabMouseClicked(evt);
            }
        });
        transactionTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        transactionListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Start Date", "End Date", "Customer Name", "Status", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionListTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(transactionListTable);

        transactionTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 746, 370));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("TRANSACTIONS");
        transactionTab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jTabbedPane1.addTab("Transactions", transactionTab);

        CategoryTab.setBackground(new java.awt.Color(255, 255, 255));
        CategoryTab.setForeground(new java.awt.Color(0, 153, 153));
        CategoryTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CategoryTab.setName("Category"); // NOI18N
        CategoryTab.setPreferredSize(new java.awt.Dimension(780, 402));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Add Category");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText(" Category Title");

        categoryNameTextField1.setBackground(new java.awt.Color(255, 255, 255));
        categoryNameTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryNameTextField1.setForeground(new java.awt.Color(0, 102, 102));

        AddCategoryButton.setBackground(new java.awt.Color(0, 102, 102));
        AddCategoryButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddCategoryButton.setText("Add");
        AddCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryButtonActionPerformed(evt);
            }
        });

        categoriesPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoriesPane.setViewportView(categoryTable);

        refreshCategoryButton1.setBackground(new java.awt.Color(0, 102, 102));
        refreshCategoryButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        refreshCategoryButton1.setText("Refresh");
        refreshCategoryButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshCategoryButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CategoryTabLayout = new javax.swing.GroupLayout(CategoryTab);
        CategoryTab.setLayout(CategoryTabLayout);
        CategoryTabLayout.setHorizontalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoryNameTextField1)
                    .addComponent(jLabel6)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5))
                    .addComponent(AddCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshCategoryButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(categoriesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        CategoryTabLayout.setVerticalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoriesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddCategoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(refreshCategoryButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Category", CategoryTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Customers");
    }// </editor-fold>//GEN-END:initComponents

    private void refreshCategoryList() {
        DefaultTableModel categoriesTableModel = (DefaultTableModel) categoryTable.getModel();

        List<Category> categories = CategoryService.getAllCategories();
        categoriesTableModel.setRowCount(0);

        System.out.println(categories.size());

        for (int i = 0; i < categories.size(); i++) {
            Category category = categories.get(i);
            Object[] rowData = {category.id, category.name};
            categoriesTableModel.addRow(rowData);
        }
    }

    private void refreshTransactionList() {
        DefaultTableModel transactionListTableModel = (DefaultTableModel) transactionListTable.getModel();
        List<Transaction> transactions = TransactionService.getAllTransactions();
        transactionListTableModel.setRowCount(0);
        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < transactions.size(); i++) {
            Transaction transaction = transactions.get(i);
            String total = "₱ " + transaction.total.toString();

            Object[] rowdata = {transaction.id, dateFormatter.format(transaction.startDate), dateFormatter.format(transaction.endDate), transaction.customer.name, transaction.status, total};
            transactionListTableModel.addRow(rowdata);
        }
    }

    private void refreshCustomerList() {
        DefaultTableModel customersTableModel = (DefaultTableModel) CustomerTable.getModel();
        List<Customer> customers = CustomerService.getAllCustomers();
        customersTableModel.setRowCount(0);

        System.out.println(customers.size());

        for (int i = 0; i < customers.size(); i++) {
            Customer customer = customers.get(i);
            Object[] rowData = {customer.id, customer.name, customer.email, customer.phone_number, customer.username, customer.address};
            customersTableModel.addRow(rowData);
        }
    }

    private void refreshEquipmentList() {
        DefaultTableModel equipmentsTableModel = (DefaultTableModel) equipmentsTable.getModel();
        Date startDate = null;
        Date endDate = null;

        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

        try {
            startDate = dateFormatter.parse("2023-11-20");
            endDate = dateFormatter.parse("2023-11-20");
        } catch (Exception e) {
        }

        List<Equipment> equipments = EquipmentService.getAllEquipments(startDate, endDate);
        equipmentsTableModel.setRowCount(0);

        Category category = null;

        if (filterComboBox.getSelectedIndex() >= 1) {
            category = CategoryService.getCategoryByName(filterComboBox.getSelectedItem().toString());
        }

        for (int i = 0; i < equipments.size(); i++) {
            Equipment equipment = equipments.get(i);
            if (category == null) {
                Object[] rowData = {equipment.id, equipment.name, equipment.description, equipment.daily_fee, equipment.weekly_fee, equipment.category.name, equipment.getIsAvailableText(), equipment.status};
                equipmentsTableModel.addRow(rowData);

            } else {
                if (category.id == equipment.category_id) {
                    Object[] rowData = {equipment.id, equipment.name, equipment.description, equipment.daily_fee, equipment.weekly_fee, equipment.category.name, equipment.getIsAvailableText(), equipment.status};
                    equipmentsTableModel.addRow(rowData);
                }
            }

        }
    }

    private void clearEquipmentForm() {

        equipmentNameInputField.setText("");
        dscriptionTextArea.setText("");
        equipmentDailyFeeInputField.setText("");
        equipmentWeeklyFeeInputField.setText("");
        equipmentCategoryCombobox.setSelectedIndex(-1);

        equipmentFormTitle.setText("Add Equipment");

    }

    private void clearCategoryForm() {
        categoryNameTextField1.setText("");
    }

    private void clearCustomerForm() {
        customerNameTextFeild1.setText("");
        customerEmailTextFeild.setText("");
        customerPhoneTextFeild.setText("");
        customerUsernameTextFeild.setText("");
        customerAddressTextFeild.setText("");
    }


    private void addEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipmentBtnActionPerformed
        String name = equipmentNameInputField.getText();

        String description = dscriptionTextArea.getText();

        String dailyFeeText = equipmentDailyFeeInputField.getText();

        String weeklFeeText = equipmentWeeklyFeeInputField.getText();

        System.out.println("Good");

        Category category = null;

        if (equipmentCategoryCombobox.getSelectedIndex() >= 0) {
            category = CategoryService.getCategoryByName(equipmentCategoryCombobox.getSelectedItem().toString());
        }

        if (name.isEmpty() || description.isEmpty() || dailyFeeText.isEmpty()
                || weeklFeeText.isEmpty() || category == null) {
            JOptionPane.showMessageDialog(null, "Please complete the form.");
        } else {
            double dailyFee = Double.parseDouble(dailyFeeText);
            double weeklyFee = Double.parseDouble(weeklFeeText);
            EquipmentService.addEquipment(name, description, dailyFee, weeklyFee, category.id);
            clearEquipmentForm();
            refreshEquipmentList();
        }
    }//GEN-LAST:event_addEquipmentBtnActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshEquipmentList();
        clearEquipmentForm();

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void updateEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEquipmentButtonActionPerformed
        // TODO add your handling code here:

        int row = equipmentsTable.getSelectedRow();
        int equipmentId = (int) equipmentsTable.getValueAt(row, 0);

        String name = (String) equipmentNameInputField.getText();
        String description = dscriptionTextArea.getText();

        String updatedDailyFeeText = equipmentDailyFeeInputField.getText();
        

        String updatedWeeklyFeeText = equipmentWeeklyFeeInputField.getText();
        
        
        Category category = CategoryService.getCategoryByName(equipmentCategoryCombobox.getSelectedItem().toString());
        String status = statusComboBox.getSelectedItem().toString();

        if (name.isEmpty() || description.isEmpty() || updatedDailyFeeText.isEmpty()
                || updatedWeeklyFeeText.isEmpty() || category == null) {
            JOptionPane.showMessageDialog(null, "Please complete the form.");
        } else {
            double updatedDailyFee = Double.parseDouble(updatedDailyFeeText);
            double updatedWeeklyFee = Double.parseDouble(updatedWeeklyFeeText);
            EquipmentService.updateEquipment(equipmentId, name, description, updatedDailyFee, updatedWeeklyFee, category.id, status);
            clearEquipmentForm();
            refreshEquipmentList();
        }


    }//GEN-LAST:event_updateEquipmentButtonActionPerformed

    private void equipmentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentsTableMouseClicked
        // TODO add your handling code here:
        int i = equipmentsTable.getSelectedRow();
        equipmentNameInputField.setText(equipmentsTable.getValueAt(i, 1).toString());
        dscriptionTextArea.setText(equipmentsTable.getValueAt(i, 2).toString());
        equipmentDailyFeeInputField.setText(equipmentsTable.getValueAt(i, 3).toString());
        equipmentWeeklyFeeInputField.setText(equipmentsTable.getValueAt(i, 4).toString());

        equipmentCategoryCombobox.setSelectedItem(equipmentsTable.getValueAt(i, 5).toString());
        statusComboBox.setSelectedItem(equipmentsTable.getValueAt(i, 7).toString());

        equipmentFormTitle.setText("Edit Equipment");
    }//GEN-LAST:event_equipmentsTableMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        refreshCustomerList();


    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void AddCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryButtonActionPerformed
        // TODO add your handling code here:
        String name = categoryNameTextField1.getText();

        if (name.equals("")) {

            JOptionPane.showMessageDialog(null, "Please complete the form.");
        } else {
            CategoryService.addCategory(name);
            clearCategoryForm();
            refreshCategoryList();
        }

    }//GEN-LAST:event_AddCategoryButtonActionPerformed

    private void refreshCategoryButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshCategoryButton1MouseClicked
        // TODO add your handling code here:
        refreshCategoryList();
        clearEquipmentForm();
    }//GEN-LAST:event_refreshCategoryButton1MouseClicked

    private void transactionTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionTabMouseClicked
        // TODO add your handling code here:
        refreshTransactionList();

    }//GEN-LAST:event_transactionTabMouseClicked

    private void transactionListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionListTableMouseClicked
        // TODO add your handling code here:
        int i = transactionListTable.getSelectedRow();
        UUID transactionId = (UUID) transactionListTable.getValueAt(i, 0);
        String total = (String) transactionListTable.getValueAt(i, 5);
        String name = (String) transactionListTable.getValueAt(i, 3);
        String startDate = "Start Date: " + (String) transactionListTable.getValueAt(i, 1);
        String endDate = "   End Date: " + (String) transactionListTable.getValueAt(i, 2);
        String status = "   Status: " + (String) transactionListTable.getValueAt(i, 4);

        List<TransactionItem> items = TransactionItemService.getTransactionItemsByTransactionId(transactionId);

        StringBuilder message = new StringBuilder();
        message.append("Transaction ID: ").append(transactionId).append("\n");
        message.append(startDate).append(endDate).append(status).append("\n\n");
        message.append("Customer Name: ").append(name).append("\n");

        for (TransactionItem item : items) {
            message.append("Equipment Name: ").append(item.equipment.name).append("\n");
            message.append("Subtotal: ₱ ").append(item.sub_total).append("\n\n");

        }
        message.append("Total: ").append(total);

        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

        Object[] options = {"Customer pick-up the equipments.", "Close"};
        if (((String) transactionListTable.getValueAt(i, 4)).equals("pending") && ((String) transactionListTable.getValueAt(i, 1)).equals(dateFormatter.format(new Date()))) {
            int choice = JOptionPane.showOptionDialog(null, message.toString(), "Transaction Details", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

            if (choice == 0) {
                TransactionService.updateTransactionStatus("ongoing", transactionId);
                refreshTransactionList();

            }
        } else {
            JOptionPane.showMessageDialog(null, message.toString(), "Transaction Details", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_transactionListTableMouseClicked

    private void equipmentCategoryComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentCategoryComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentCategoryComboboxActionPerformed

    private void filterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterComboBoxItemStateChanged
        // TODO add your handling code here:
        refreshEquipmentList();
    }//GEN-LAST:event_filterComboBoxItemStateChanged

    private void equipmentDailyFeeInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentDailyFeeInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentDailyFeeInputFieldActionPerformed

    private void refreshCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCustomerButton1ActionPerformed
        // TODO add your handling code here:
        refreshCustomerList();
    }//GEN-LAST:event_refreshCustomerButton1ActionPerformed

    private void UpdateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerButtonActionPerformed
        // TODO add your handling code here:
        int row = CustomerTable.getSelectedRow();
        int id = (int) CustomerTable.getValueAt(row, 0);

        String name = (String) customerNameTextFeild1.getText();
        String email = (String) customerEmailTextFeild.getText();
        String phone_number = (String) customerPhoneTextFeild.getText();
        String username = (String) customerUsernameTextFeild.getText();
        String address = (String) customerAddressTextFeild.getText();

        CustomerService.updateCustomer(id, name, email, phone_number, username, address);
        refreshCustomerList();
        clearCustomerForm();
    }//GEN-LAST:event_UpdateCustomerButtonActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        // TODO add your handling code here:
        int i = CustomerTable.getSelectedRow();

        customerNameTextFeild1.setText(CustomerTable.getValueAt(i, 1).toString());
        customerEmailTextFeild.setText(CustomerTable.getValueAt(i, 2).toString());
        customerPhoneTextFeild.setText(CustomerTable.getValueAt(i, 3).toString());
        customerUsernameTextFeild.setText(CustomerTable.getValueAt(i, 4).toString());
        customerAddressTextFeild.setText(CustomerTable.getValueAt(i, 5).toString());
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void log_outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outButtonActionPerformed
        // TODO add your handling code here:

        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            JFrame frame = new JFrame("Film Equipment Rental Service");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new CustomerLogin()); // Add the Login panel to the frame
            frame.pack(); // Resize the frame to fit the component
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_log_outButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCategoryButton;
    private javax.swing.JPanel CategoryTab;
    private javax.swing.JScrollPane CustomerPane;
    private javax.swing.JPanel CustomerTab;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JLabel EqupmentNameLabel1;
    private javax.swing.JLabel EqupmentNameLabel2;
    private javax.swing.JLabel EqupmentNameLabel3;
    private javax.swing.JButton UpdateCustomerButton;
    private javax.swing.JButton addEquipmentBtn;
    private javax.swing.JScrollPane categoriesPane;
    private javax.swing.JTextField categoryNameTextField1;
    private javax.swing.JTable categoryTable;
    private javax.swing.JTextField customerAddressTextFeild;
    private javax.swing.JLabel customerEmailLabel2;
    private javax.swing.JTextField customerEmailTextFeild;
    private javax.swing.JTextField customerNameTextFeild1;
    private javax.swing.JTextField customerPhoneTextFeild;
    private javax.swing.JTextField customerUsernameTextFeild;
    private javax.swing.JTextArea dscriptionTextArea;
    private javax.swing.JComboBox<String> equipmentCategoryCombobox;
    private javax.swing.JTextField equipmentDailyFeeInputField;
    private javax.swing.JLabel equipmentFormTitle;
    private javax.swing.JTextField equipmentNameInputField;
    private javax.swing.JPanel equipmentTab;
    private javax.swing.JTextField equipmentWeeklyFeeInputField;
    private javax.swing.JTable equipmentsTable;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton log_outButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshCategoryButton1;
    private javax.swing.JButton refreshCustomerButton1;
    private javax.swing.JScrollPane scrollpaneDescription;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTable transactionListTable;
    private javax.swing.JPanel transactionTab;
    private javax.swing.JLabel ucstomerNameLabel1;
    private javax.swing.JLabel ucstomerNameLabel2;
    private javax.swing.JLabel ucstomerNameLabel3;
    private javax.swing.JLabel ucstomerNameLabel4;
    private javax.swing.JButton updateEquipmentButton;
    // End of variables declaration//GEN-END:variables
}
