/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.filmequipmentrentalservice;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil Patrick
 */
public class AdminDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AdminDashBoard() {
        initComponents();
        refreshEquipmentList();
        
        List<Category> categories = CategoryService.getAllCategories();
        
        for (int i = 0; i < categories.size(); i++) {
            equipmentCategoryCombobox.addItem(categories.get(i).name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        equipmentTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipmentsTable = new javax.swing.JTable();
        EqupmentNameLabel1 = new javax.swing.JLabel();
        EqupmentNameLabel2 = new javax.swing.JLabel();
        EqupmentNameLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        equipmentDailyFeeInputField = new javax.swing.JTextField();
        equipmentNameInputField = new javax.swing.JTextField();
        equipmentDescriptionInputField = new javax.swing.JTextField();
        equipmentWeeklyFeeInputField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addEquipmentBtn = new javax.swing.JButton();
        deleteCustomerButton1 = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        updateEquipmentButton = new javax.swing.JButton();
        equipmentCategoryCombobox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 75, 75));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 65));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Film Equipment Rental Service");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setName("Customers"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 425));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jPanel2.setName("Customers"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 325));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Customers", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.setName("Category"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(780, 402));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Category", jPanel4);

        equipmentTab.setBackground(new java.awt.Color(255, 255, 255));
        equipmentTab.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Add Equipments");

        equipmentsTable.setAutoCreateRowSorter(true);
        equipmentsTable.setBackground(new java.awt.Color(255, 255, 255));
        equipmentsTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        equipmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipment ID", "Equipment Name", "Description", "Daily Fee", "Weekly Fee", "CAtegory ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        equipmentsTable.setPreferredSize(new java.awt.Dimension(300, 300));
        equipmentsTable.setRequestFocusEnabled(false);
        equipmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(equipmentsTable);
        if (equipmentsTable.getColumnModel().getColumnCount() > 0) {
            equipmentsTable.getColumnModel().getColumn(0).setHeaderValue("Equipment ID");
            equipmentsTable.getColumnModel().getColumn(1).setHeaderValue("Equipment Name");
            equipmentsTable.getColumnModel().getColumn(2).setHeaderValue("Description");
            equipmentsTable.getColumnModel().getColumn(3).setHeaderValue("Daily Fee");
            equipmentsTable.getColumnModel().getColumn(4).setHeaderValue("Weekly Fee");
            equipmentsTable.getColumnModel().getColumn(5).setHeaderValue("CAtegory ID");
        }

        EqupmentNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel1.setText("Equipment Name");

        EqupmentNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel2.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel2.setText("Description");

        EqupmentNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EqupmentNameLabel3.setForeground(new java.awt.Color(0, 102, 102));
        EqupmentNameLabel3.setText("Daily Fee");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Weekly Fee");

        equipmentDailyFeeInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentDailyFeeInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentDailyFeeInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        equipmentNameInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentNameInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentNameInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        equipmentDescriptionInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentDescriptionInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentDescriptionInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        equipmentWeeklyFeeInputField.setBackground(new java.awt.Color(255, 255, 255));
        equipmentWeeklyFeeInputField.setForeground(new java.awt.Color(0, 102, 102));
        equipmentWeeklyFeeInputField.setMinimumSize(new java.awt.Dimension(4, 19));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Category");

        addEquipmentBtn.setText("Add");
        addEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEquipmentBtnActionPerformed(evt);
            }
        });

        deleteCustomerButton1.setText("Delete");
        deleteCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButton1ActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        updateEquipmentButton.setText("Update");
        updateEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEquipmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipmentTabLayout = new javax.swing.GroupLayout(equipmentTab);
        equipmentTab.setLayout(equipmentTabLayout);
        equipmentTabLayout.setHorizontalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(equipmentTabLayout.createSequentialGroup()
                                .addComponent(equipmentCategoryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))
                            .addGroup(equipmentTabLayout.createSequentialGroup()
                                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(equipmentTabLayout.createSequentialGroup()
                                        .addComponent(EqupmentNameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(102, 102, 102))
                                    .addComponent(equipmentNameInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(equipmentDescriptionInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(equipmentDailyFeeInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EqupmentNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(equipmentWeeklyFeeInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(equipmentTabLayout.createSequentialGroup()
                                        .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(EqupmentNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(20, 20, 20))))
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(addEquipmentBtn)
                        .addGap(72, 72, 72)))
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(deleteCustomerButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateEquipmentButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        equipmentTabLayout.setVerticalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(EqupmentNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqupmentNameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentDescriptionInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqupmentNameLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentDailyFeeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipmentWeeklyFeeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(equipmentTabLayout.createSequentialGroup()
                            .addComponent(deleteCustomerButton1)
                            .addGap(379, 379, 379))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, equipmentTabLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(refreshButton)
                                .addComponent(updateEquipmentButton))
                            .addGap(368, 368, 368)))
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipmentCategoryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(addEquipmentBtn)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Equipments", equipmentTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Customers");
    }// </editor-fold>//GEN-END:initComponents

    private void refreshEquipmentList() {
        DefaultTableModel equipmentsTableModel = (DefaultTableModel) equipmentsTable.getModel();
        List<Equipment> equipments = EquipmentService.getAllEquipments();
        equipmentsTableModel.setRowCount(0);
        
        System.out.println(equipments.size());
        
        for (int i = 0; i < equipments.size(); i++) {
            Equipment equipment = equipments.get(i);
            Object[] rowData = {equipment.id, equipment.name, equipment.description, equipment.daily_fee, equipment.weekly_fee, equipment.category.name};
            equipmentsTableModel.addRow(rowData);
        }
    }
    
    private void clearEquipmentForm() {
        equipmentNameInputField.setText("");
        equipmentDescriptionInputField.setText("");
        equipmentDailyFeeInputField.setText("");
        equipmentWeeklyFeeInputField.setText("");
        equipmentCategoryCombobox.setSelectedIndex(-1);
    }

    private void addEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipmentBtnActionPerformed
        String name = equipmentNameInputField.getText();
        String description = equipmentDescriptionInputField.getText();
        
        String dailyFeeText = equipmentDailyFeeInputField.getText();
        double dailyFee = Double.parseDouble(dailyFeeText);
        
        String weeklFeeText = equipmentWeeklyFeeInputField.getText();
        double weeklyFee = Double.parseDouble(weeklFeeText);
        
        Category category = null;
        
        if (equipmentCategoryCombobox.getSelectedIndex() >= 0) {
            category = CategoryService.getCategoryByName(equipmentCategoryCombobox.getSelectedItem().toString());
        }
        
        if (name.equals("") || description.equals("") || dailyFeeText.equals("")
                || weeklFeeText.equals("") || category == null) {
            JOptionPane.showMessageDialog(null, "Please complete the form.");
        } else {
            EquipmentService.addEquipment(name, description, dailyFee, weeklyFee, category.id);
            clearEquipmentForm();
            refreshEquipmentList();
        }
    }//GEN-LAST:event_addEquipmentBtnActionPerformed

    private void deleteCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButton1ActionPerformed
        // TODO add your handling code here: 

        int row = equipmentsTable.getSelectedRow();
        int equipmentId = (int) equipmentsTable.getValueAt(row, 0);
        System.out.println(equipmentId);
        
        EquipmentService.deleteEquipment(equipmentId);
        clearEquipmentForm();
        refreshEquipmentList();
        

    }//GEN-LAST:event_deleteCustomerButton1ActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshEquipmentList();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void updateEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEquipmentButtonActionPerformed
        // TODO add your handling code here:

        int row = equipmentsTable.getSelectedRow();
        int equipmentId = (int) equipmentsTable.getValueAt(row, 0);
        
        String name = (String) equipmentsTable.getValueAt(row, 1);
        String description = (String) equipmentsTable.getValueAt(row, 2);
        
        String updatedDailyFeeText = equipmentDailyFeeInputField.getText();
        double updatedDailyFee = Double.parseDouble(updatedDailyFeeText);
        
        String updatedWeeklyFeeText = equipmentWeeklyFeeInputField.getText();
        double updatedWeeklyFee = Double.parseDouble(updatedWeeklyFeeText);
        
        int categoryID = (int) equipmentsTable.getValueAt(row, 4);
        
        EquipmentService.updateEquipment(equipmentId, name, description, updatedDailyFee, updatedWeeklyFee, categoryID);
        
        clearEquipmentForm();
        refreshEquipmentList();
    }//GEN-LAST:event_updateEquipmentButtonActionPerformed

    private void equipmentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentsTableMouseClicked
        // TODO add your handling code here:
        int i = equipmentsTable.getSelectedRow();
        equipmentNameInputField.setText(equipmentsTable.getValueAt(i, 1).toString());
        equipmentDescriptionInputField.setText(equipmentsTable.getValueAt(i, 2).toString());
        equipmentDailyFeeInputField.setText(equipmentsTable.getValueAt(i, 3).toString());
        equipmentWeeklyFeeInputField.setText(equipmentsTable.getValueAt(i, 4).toString());
        
        equipmentCategoryCombobox.setSelectedItem(equipmentsTable.getValueAt(i, 5).toString());
    }//GEN-LAST:event_equipmentsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EqupmentNameLabel1;
    private javax.swing.JLabel EqupmentNameLabel2;
    private javax.swing.JLabel EqupmentNameLabel3;
    private javax.swing.JButton addEquipmentBtn;
    private javax.swing.JButton deleteCustomerButton1;
    private javax.swing.JComboBox<String> equipmentCategoryCombobox;
    private javax.swing.JTextField equipmentDailyFeeInputField;
    private javax.swing.JTextField equipmentDescriptionInputField;
    private javax.swing.JTextField equipmentNameInputField;
    private javax.swing.JPanel equipmentTab;
    private javax.swing.JTextField equipmentWeeklyFeeInputField;
    private javax.swing.JTable equipmentsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton updateEquipmentButton;
    // End of variables declaration//GEN-END:variables
}
