/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.filmequipmentrentalservice;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Neil Patrick
 */
public class CustomerDashboardFrame extends javax.swing.JFrame {

    Transaction cart;
    Customer authCustomer;

    /**
     * Creates new form dashboardFrame
     */
    public CustomerDashboardFrame() {
        initComponents();
        refreshEquipmentList();
        refreshTransactionList();
    }

//    UUID id, Date startDate, Date endDate, int customer_id, String status, Double total, List<TransactionItem> items
    public void setAuthCustomer(Customer authCustomer) {
        this.authCustomer = authCustomer;
        this.cart = new Transaction(UUID.randomUUID(), null, null, this.authCustomer.id, "pending", 0.0, new ArrayList<TransactionItem>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Right = new javax.swing.JPanel();
        HomeBUtton = new javax.swing.JButton();
        EquipmmentButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        startDate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        allEquipmentScroolPane = new javax.swing.JScrollPane();
        equipmentsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SearchTextFeild = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        endDatePicker = new com.toedter.calendar.JDateChooser();
        startDatePicker = new com.toedter.calendar.JDateChooser();
        myCartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myCartTable = new javax.swing.JTable();
        removeAllButton = new javax.swing.JButton();
        cartDurationLabel = new javax.swing.JLabel();
        cartTotalLabel = new javax.swing.JLabel();
        checkOutButton1 = new javax.swing.JButton();
        myRentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTransactionLIstTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Dashbard");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Right.setPreferredSize(new java.awt.Dimension(250, 680));

        HomeBUtton.setBackground(new java.awt.Color(255, 255, 255));
        HomeBUtton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HomeBUtton.setForeground(new java.awt.Color(0, 102, 102));
        HomeBUtton.setText("Home");
        HomeBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBUttonActionPerformed(evt);
            }
        });

        EquipmmentButton.setBackground(new java.awt.Color(255, 255, 255));
        EquipmmentButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        EquipmmentButton.setForeground(new java.awt.Color(0, 102, 102));
        EquipmmentButton.setText("My Cart");
        EquipmmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmmentButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("My  Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Button");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeBUtton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipmmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(HomeBUtton)
                .addGap(18, 18, 18)
                .addComponent(EquipmmentButton)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        getContentPane().add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        startDate.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Rent Equipment ");

        allEquipmentScroolPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        equipmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Daily Fee", "Weekly Fee", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentsTable.setGridColor(new java.awt.Color(0, 102, 102));
        equipmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentsTableMouseClicked(evt);
            }
        });
        allEquipmentScroolPane.setViewportView(equipmentsTable);
        if (equipmentsTable.getColumnModel().getColumnCount() > 0) {
            equipmentsTable.getColumnModel().getColumn(0).setMinWidth(30);
            equipmentsTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            equipmentsTable.getColumnModel().getColumn(0).setMaxWidth(30);
            equipmentsTable.getColumnModel().getColumn(2).setMinWidth(325);
            equipmentsTable.getColumnModel().getColumn(2).setPreferredWidth(325);
            equipmentsTable.getColumnModel().getColumn(2).setMaxWidth(325);
            equipmentsTable.getColumnModel().getColumn(2).setHeaderValue("Description");
            equipmentsTable.getColumnModel().getColumn(3).setHeaderValue("Daily Fee");
        }

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Search Equipent.");

        SearchTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        SearchTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchTextFeild.setForeground(new java.awt.Color(0, 102, 102));
        SearchTextFeild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTextFeildKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Start date");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("End date");

        endDatePicker.setBackground(new java.awt.Color(255, 255, 255));
        endDatePicker.setForeground(new java.awt.Color(0, 0, 0));
        endDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endDatePickerPropertyChange(evt);
            }
        });

        startDatePicker.setBackground(new java.awt.Color(255, 255, 255));
        startDatePicker.setForeground(new java.awt.Color(0, 0, 0));
        startDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startDatePickerPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout startDateLayout = new javax.swing.GroupLayout(startDate);
        startDate.setLayout(startDateLayout);
        startDateLayout.setHorizontalGroup(
            startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startDateLayout.createSequentialGroup()
                        .addComponent(allEquipmentScroolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(startDateLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startDateLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(startDateLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel9)
                                .addGap(3, 3, 3)
                                .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(startDateLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        startDateLayout.setVerticalGroup(
            startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startDateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SearchTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startDateLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(startDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allEquipmentScroolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab2", startDate);

        myCartPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("My Cart");

        myCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipment Name", "Category", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myCartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCartTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myCartTable);
        if (myCartTable.getColumnModel().getColumnCount() > 0) {
            myCartTable.getColumnModel().getColumn(0).setMinWidth(35);
            myCartTable.getColumnModel().getColumn(0).setPreferredWidth(35);
            myCartTable.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        removeAllButton.setBackground(new java.awt.Color(0, 102, 102));
        removeAllButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        removeAllButton.setLabel("Remove all");
        removeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllButtonActionPerformed(evt);
            }
        });

        cartDurationLabel.setText("   ");

        cartTotalLabel.setText("   ");

        checkOutButton1.setBackground(new java.awt.Color(0, 102, 102));
        checkOutButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkOutButton1.setText("Check out");
        checkOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myCartPanelLayout = new javax.swing.GroupLayout(myCartPanel);
        myCartPanel.setLayout(myCartPanelLayout);
        myCartPanelLayout.setHorizontalGroup(
            myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myCartPanelLayout.createSequentialGroup()
                .addGroup(myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myCartPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                            .addGroup(myCartPanelLayout.createSequentialGroup()
                                .addGroup(myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cartDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cartTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 14, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myCartPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        myCartPanelLayout.setVerticalGroup(
            myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(myCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeAllButton)
                    .addComponent(checkOutButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", myCartPanel);

        myRentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        customerTransactionLIstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Start Date", "End Date", "Customer Name", "Status", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTransactionLIstTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTransactionLIstTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(customerTransactionLIstTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("MY TRANSACTION");

        javax.swing.GroupLayout myRentPanelLayout = new javax.swing.GroupLayout(myRentPanel);
        myRentPanel.setLayout(myRentPanelLayout);
        myRentPanelLayout.setHorizontalGroup(
            myRentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myRentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myRentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addGroup(myRentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        myRentPanelLayout.setVerticalGroup(
            myRentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myRentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab3", myRentPanel);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("My rent");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel4)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab4", jPanel4);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -30, 760, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTransactionList() {
        DefaultTableModel transactionListTableModel = (DefaultTableModel) customerTransactionLIstTable.getModel();
        transactionListTableModel.setRowCount(0);

        if (this.authCustomer == null) {
            return;
        }
        List<Transaction> transactions = TransactionService.getTransactionsByCustomerId(this.authCustomer.id);

        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < transactions.size(); i++) {
            Transaction transaction = transactions.get(i);

            String total = "₱ " + transaction.total.toString();
            Object[] rowdata = {transaction.id, dateFormatter.format(transaction.startDate), dateFormatter.format(transaction.endDate), transaction.customer.name, transaction.status, total, transaction.items};
            transactionListTableModel.addRow(rowdata);
        }
    }

    private void refreshEquipmentList() {
        DefaultTableModel equipmentsTableModel = (DefaultTableModel) equipmentsTable.getModel();
        List<Equipment> equipments = EquipmentService.getAllEquipments();
        equipmentsTableModel.setRowCount(0);

        System.out.println(equipments.size());

        for (int i = 0; i < equipments.size(); i++) {
            Equipment equipment = equipments.get(i);
            Object[] rowData = {equipment.id, equipment.name, equipment.description, equipment.daily_fee, equipment.weekly_fee, equipment.category.name};
            equipmentsTableModel.addRow(rowData);
        }

        equipmentsTable.setRowSorter(null); // reset the table sort
        SearchTextFeild.setText(""); // reset search text feild

    }

    private void refreshCartList() {
        DefaultTableModel cartTableModel = (DefaultTableModel) myCartTable.getModel();
        cartTableModel.setRowCount(0);

        for (int i = 0; i < this.cart.items.size(); i++) {
            TransactionItem item = this.cart.items.get(i);
            Object[] rowData = {item.equipment.id, item.equipment.name, item.equipment.category.name, item.sub_total};
            cartTableModel.addRow(rowData);
        }

        equipmentsTable.setRowSorter(null); // reset the table sort
        SearchTextFeild.setText(""); // reset search text feild

    }


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void HomeBUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBUttonActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_HomeBUttonActionPerformed

    private void EquipmmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmmentButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_EquipmmentButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
        refreshTransactionList();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void SearchTextFeildKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextFeildKeyPressed
        // TODO add your handling code here:
        DefaultTableModel obj = (DefaultTableModel) equipmentsTable.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        equipmentsTable.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(SearchTextFeild.getText()));

    }//GEN-LAST:event_SearchTextFeildKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refreshEquipmentList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void equipmentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentsTableMouseClicked
        int i = equipmentsTable.getSelectedRow();
        int id = (int) equipmentsTable.getValueAt(i, 0);

        if (this.cart.getNumberOfDays() <= 0) {
            return;
        }

        if (!this.cart.isEquipmentAlreadyAdded(id)) {
            int response = JOptionPane.showConfirmDialog(this, "Do you want to add this?", "Select Option", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Equipment equipment = EquipmentService.getEquipmentById(id);
                TransactionItem item = new TransactionItem(UUID.randomUUID(), this.cart.id, equipment.id, equipment.daily_fee * this.cart.getNumberOfDays());
                item.setEquipment(equipment);
                this.cart.addItem(item);
                refreshCartList();
                updateCartSummary();
            }
        }
    }//GEN-LAST:event_equipmentsTableMouseClicked

    private void removeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to remove this?", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            this.cart.clearItems();
            refreshCartList();
            updateCartSummary();
        }
    }//GEN-LAST:event_removeAllButtonActionPerformed

    private void myCartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCartTableMouseClicked
        // TODO add your handling code here:
        int i = myCartTable.getSelectedRow();
        int response = JOptionPane.showConfirmDialog(this, "Do you want to remove this?", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            this.cart.removeItem(i);
            refreshCartList();
            updateCartSummary();
        }
    }//GEN-LAST:event_myCartTableMouseClicked

    private void startDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startDatePickerPropertyChange
        Date startDate = startDatePicker.getDate();

        if (startDate != null) {
            this.cart.setStartDate(startDate);
        }

        updateCartSummary();
    }//GEN-LAST:event_startDatePickerPropertyChange

    private void endDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endDatePickerPropertyChange
        Date endDate = endDatePicker.getDate();

        if (endDate != null) {
            this.cart.setEndDate(endDate);
        }

        updateCartSummary();
    }//GEN-LAST:event_endDatePickerPropertyChange

    private void checkOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButton1ActionPerformed
        TransactionService.saveTransaction(this.cart);
        for (TransactionItem item : this.cart.items) {
            TransactionItemService.saveTransactionItem(item);
        }
        JOptionPane.showMessageDialog(null, "Succesful!");

        // JOptionPane.showConfirmDialog(this, "Success! ", "Select Option ", JOptionPane.OK_OPTION);
        this.cart.clearItems();
        refreshCartList();
        updateCartSummary();


    }//GEN-LAST:event_checkOutButton1ActionPerformed

    private void customerTransactionLIstTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTransactionLIstTableMouseClicked
        // TODO add your handling code here:
        int i = customerTransactionLIstTable.getSelectedRow();
    UUID transactionId = (UUID) customerTransactionLIstTable.getValueAt(i, 0);
    String total = "₱ " + (String) customerTransactionLIstTable.getValueAt(i, 5);

    List<TransactionItem> items = TransactionItemService.getTransactionItemsByTransactionId(transactionId);

    StringBuilder message = new StringBuilder();
    message.append("Transaction ID: ").append(transactionId).append("\n\n");

    for (TransactionItem item : items) {
        message.append("Equipment Name: ").append(item.equipment.name).append("\n");
        message.append("Subtotal: ").append(item.sub_total).append("\n\n");
        
    }
    message.append("Total: ").append(total);

    JOptionPane.showMessageDialog(null, message.toString(), "Transaction Items", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_customerTransactionLIstTableMouseClicked

    public void updateCartSummary() {
        if (this.cart == null) {
            return;
        }

        if (this.cart.startDate != null && this.cart.endDate != null) {
            cartDurationLabel.setText(this.cart.startDate.toString() + " - " + this.cart.endDate.toString());
        }

        cartTotalLabel.setText("Total: " + this.cart.total.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EquipmmentButton;
    private javax.swing.JButton HomeBUtton;
    private javax.swing.JPanel Right;
    private javax.swing.JTextField SearchTextFeild;
    private javax.swing.JScrollPane allEquipmentScroolPane;
    private javax.swing.JLabel cartDurationLabel;
    private javax.swing.JLabel cartTotalLabel;
    private javax.swing.JButton checkOutButton1;
    private javax.swing.JTable customerTransactionLIstTable;
    private com.toedter.calendar.JDateChooser endDatePicker;
    private javax.swing.JTable equipmentsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel myCartPanel;
    private javax.swing.JTable myCartTable;
    private javax.swing.JPanel myRentPanel;
    private javax.swing.JButton removeAllButton;
    private javax.swing.JPanel startDate;
    private com.toedter.calendar.JDateChooser startDatePicker;
    // End of variables declaration//GEN-END:variables
}
