/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.filmequipmentrentalservice;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Neil Patrick
 */
public class CustomerLogin extends javax.swing.JPanel {

    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();

        loginAsCustomerRadioBtn.setSelected(true);
        loginAsButtonGroup.add(loginAsAdminRadioBtn);
        loginAsButtonGroup.add(loginAsCustomerRadioBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAsButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernamerTextfeild = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginAsCustomerRadioBtn = new javax.swing.JRadioButton();
        loginAsAdminRadioBtn = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neil Patrick\\Downloads\\1130456-removebg-preview (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LOGIN");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 102, 102));
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 102, 102));
        passwordLabel.setText("Password");

        usernamerTextfeild.setBackground(new java.awt.Color(255, 255, 255));
        usernamerTextfeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamerTextfeild.setForeground(new java.awt.Color(0, 102, 102));

        loginButton.setBackground(new java.awt.Color(0, 102, 102));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        signupButton.setBackground(new java.awt.Color(255, 255, 255));
        signupButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        signupButton.setForeground(new java.awt.Color(0, 75, 75));
        signupButton.setText("I dont have an Account");
        signupButton.setBorder(null);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 102, 102));

        loginAsCustomerRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginAsCustomerRadioBtn.setForeground(new java.awt.Color(0, 102, 102));
        loginAsCustomerRadioBtn.setText("Login as customer");
        loginAsCustomerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsCustomerRadioBtnActionPerformed(evt);
            }
        });

        loginAsAdminRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginAsAdminRadioBtn.setForeground(new java.awt.Color(0, 102, 102));
        loginAsAdminRadioBtn.setText("Login as admin");
        loginAsAdminRadioBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loginAsAdminRadioBtnStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernamerTextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(passwordLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(loginAsCustomerRadioBtn)
                                            .addGap(31, 31, 31)
                                            .addComponent(loginAsAdminRadioBtn))
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(signupButton)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(loginButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamerTextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginAsCustomerRadioBtn)
                    .addComponent(loginAsAdminRadioBtn))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

//    public void close() {
//
//        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
//    }

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Boolean isCustomer = loginAsCustomerRadioBtn.isSelected();

        String username = usernamerTextfeild.getText();
        char[] passwordChars = jPasswordField1.getPassword();
        String password = new String(passwordChars);

        if (isCustomer) {
            Customer customer = CustomerService.getByUsernameAndPassword(username, password);
            if (customer == null) {
                JOptionPane.showMessageDialog(null, "Wrong username or password.", "Message", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("test");

                JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                this.setVisible(false);
                mainFrame.remove(this);
                mainFrame.dispose();

                CustomerDashboardFrame CustomerDash = new CustomerDashboardFrame();
                CustomerDash.setAuthCustomer(customer);
                CustomerDash.setVisible(true);
                CustomerDash.setLocationRelativeTo(null);
            }
        } else {
            Admin admin = AdminService.getByUsernameAndPassword(username, password);
            if (admin == null) {
                JOptionPane.showMessageDialog(null, "Wrong username or password.", "Message", JOptionPane.ERROR_MESSAGE);
            } else {
                JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                mainFrame.remove(this);
                AdminDashBoard pan = new AdminDashBoard();
                mainFrame.add(pan);

                mainFrame.revalidate();
                mainFrame.repaint();
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        this.setVisible(false);
        mainFrame.remove(this);
        CustomerSignup pan = new CustomerSignup();
        mainFrame.add(pan);

        mainFrame.revalidate();
        mainFrame.repaint();

        System.out.print(mainFrame);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginAsCustomerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAsCustomerRadioBtnActionPerformed
        // TODO add your handling code here:
        boolean isCustomer = loginAsCustomerRadioBtn.isSelected();
        signupButton.setEnabled(isCustomer);
    }//GEN-LAST:event_loginAsCustomerRadioBtnActionPerformed

    private void loginAsAdminRadioBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loginAsAdminRadioBtnStateChanged
        // TODO add your handling code here:
        boolean isCustomer = loginAsCustomerRadioBtn.isSelected();
        signupButton.setEnabled(isCustomer);
    }//GEN-LAST:event_loginAsAdminRadioBtnStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton loginAsAdminRadioBtn;
    private javax.swing.ButtonGroup loginAsButtonGroup;
    private javax.swing.JRadioButton loginAsCustomerRadioBtn;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernamerTextfeild;
    // End of variables declaration//GEN-END:variables
}
